services:
  mongodb-primary:
    image: bitnami/mongodb:latest
    container_name: mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27017:27017
    volumes:
      - mongodb_master_data:/bitnami
    networks:
      - manga-dev-network

  mongodb-secondary:
    image: bitnami/mongodb:latest
    container_name: mongodb-secondary
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27027:27017
    networks:
      - manga-dev-network

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    container_name: mongodb-arbiter
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27037:27017
    networks:
      - manga-dev-network

  browserless_dev:
    image: browserless/chrome
    container_name: browserless-dev
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - DEFAULT_BLOCK_ADS=true
      - MAX_CONCURRENT_SESSIONS=5
      - PREBOOT_CHROME=true
    networks:
      - manga-dev-network

volumes:
  mongodb_master_data:
    driver: local

networks:
  manga-dev-network:
    driver: bridge
