services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DATABASE_URL
      - SESSION_SECRET
      - UPLOADTHING_TOKEN
      - BROWSERLESS_URL
    depends_on:
      - browserless
    container_name: manga-xr-app
    networks:
      - manga-network

  browserless:
    image: browserless/chrome
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - DEFAULT_BLOCK_ADS=true
      - MAX_CONCURRENT_SESSIONS=5
      - PREBOOT_CHROME=true
    container_name: browserless
    networks:
      - manga-network

networks:
  manga-network:
    driver: bridge
