services:
  app:
    image: friedrich18/manga-xr-app:latest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../../.env.production
    depends_on:
      - browserless
    container_name: manga-xr-app
    networks:
      - manga-network

  browserless:
    image: ghcr.io/browserless/chromium:latest
    environment:
      - DEFAULT_BLOCK_ADS=true
      - MAX_CONCURRENT_SESSIONS=5
      - PREBOOT_CHROME=true
    container_name: browserless
    networks:
      - manga-network

networks:
  manga-network:
    driver: bridge
