services:
  app:
    image: friedrich18/manga-xr-app:latest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../../.env.production
    depends_on:
      - browserless
    container_name: manga-xr-app
    networks:
      - manga-network

  protonvpn:
    image: ghcr.io/tprasadtp/protonwire:latest
    container_name: protonvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - ../../.env.production
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - type: bind
        source: private.key
        target: /etc/protonwire/private-key
        read_only: true
    tty: true
    networks:
      - vpn-network

  browserless:
    image: ghcr.io/browserless/chromium:latest
    environment:
      - DEFAULT_BLOCK_ADS=true
      - MAX_CONCURRENT_SESSIONS=5
      - PREBOOT_CHROME=true
    container_name: browserless
    network_mode: "service:protonvpn" 

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      vpn-network: {}
      manga-network: {}

networks:
  vpn-network:
    driver: bridge
  manga-network:
    driver: bridge
